import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    // No kotlin-android: AGP 9 builds Kotlin itself (built-in Kotlin). These two are compiler plugins.
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// ── Hosts ────────────────────────────────────────────────────────────────────────────────
// The public host lives in ONE place in android/: here. (Web: src/lib/site.ts · iOS: project.yml.)
val kuraPublicHost = "get-kura.app"
// Debug: the Mac's dev server seen from the emulator (10.0.2.2 = host loopback), started with
// `pnpm dev --port 3010`. `-PkuraApiHost=192.168.1.20:3010` points a debug build at the Mac by IP
// (physical phone on the same wifi). Always http: debug only, cleartext allowed for that host alone.
val kuraDebugApiHost: String = providers.gradleProperty("kuraApiHost").orNull
    ?.takeIf { it.isNotBlank() } ?: "10.0.2.2:3010"

// Parallel lanes: `-PkuraAppIdSuffix=.lane` → com.tromwey.kura.lane (debug only), so several
// variants can live side by side on one emulator.
val kuraAppIdSuffix: String? = providers.gradleProperty("kuraAppIdSuffix").orNull
    ?.takeIf { it.isNotBlank() }
    ?.let { if (it.startsWith(".")) it else ".$it" }

android {
    namespace = "com.tromwey.kura"
    // 37 because material3 1.5 (Expressive), Compose 1.12, core 1.19 and okhttp 5.5 demand it
    // (aar-metadata minCompileSdk=37). targetSdk stays 36: targeting 37 is its own lane.
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "com.tromwey.kura" // same id as the iOS bundle
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        // Shared links always point at the public site, in every build type.
        buildConfigField("String", "SITE_URL", "\"https://$kuraPublicHost\"")
    }

    // Spanish-only app (es-MX, like iOS): don't ship the other locales AndroidX brings along.
    androidResources {
        localeFilters += "es"
    }

    buildTypes {
        debug {
            buildConfigField("String", "API_BASE", "\"http://$kuraDebugApiHost/api/v1\"")
            manifestPlaceholders["networkSecurityConfig"] = "@xml/network_security_config_debug"
            kuraAppIdSuffix?.let {
                applicationIdSuffix = it
                versionNameSuffix = "-" + it.removePrefix(".")
            }
            resValue("string", "app_name", kuraAppIdSuffix?.let { "kura ${it.removePrefix(".")}" } ?: "kura")
        }
        release {
            buildConfigField("String", "API_BASE", "\"https://$kuraPublicHost/api/v1\"")
            manifestPlaceholders["networkSecurityConfig"] = "@xml/network_security_config"
            resValue("string", "app_name", "kura")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // Unsigned for now (Play signing is a later lane): assembleRelease → app-release-unsigned.apk
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
        // AGP 9 turned resValues off by default; app_name is a resValue per build type (lane name).
        resValues = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/INDEX.LIST"
            excludes += "/META-INF/io.netty.versions.properties"
        }
    }
}

// Built-in Kotlin: jvmTarget follows compileOptions.targetCompatibility (17); kept explicit so the
// bytecode level never drifts silently if the Java side changes.
kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

// Debug network security config: cleartext ONLY for the dev hosts (emulator loopback, localhost
// and whatever -PkuraApiHost names). Generated per build so a phone pointed at the Mac's IP works
// without widening cleartext to every host. Release uses src/main/res/xml/network_security_config.xml
// (no cleartext at all).
abstract class DebugNetworkSecurityConfigTask : DefaultTask() {
    @get:Input abstract val hosts: SetProperty<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val domains = hosts.get().sorted().joinToString("\n") {
            "        <domain includeSubdomains=\"false\">$it</domain>"
        }
        val file = outputDir.get().file("xml/network_security_config_debug.xml").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- GENERATED by :app:generateDebugNetworkSecurityConfig — edit app/build.gradle.kts, not this file. -->
            |<network-security-config>
            |    <base-config cleartextTrafficPermitted="false" />
            |    <domain-config cleartextTrafficPermitted="true">
            |$domains
            |    </domain-config>
            |</network-security-config>
            |""".trimMargin(),
        )
    }
}

val generateDebugNetworkSecurityConfig = tasks.register<DebugNetworkSecurityConfigTask>("generateDebugNetworkSecurityConfig") {
    hosts.set(setOf("10.0.2.2", "localhost", "127.0.0.1", kuraDebugApiHost.substringBefore(':')))
    outputDir.set(layout.buildDirectory.dir("generated/kura/debugNetworkSecurityConfig"))
}

androidComponents {
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.sources.res?.addGeneratedSourceDirectory(
            generateDebugNetworkSecurityConfig,
            DebugNetworkSecurityConfigTask::outputDir,
        )
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.core.splashscreen)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.palette.ktx)
    implementation(libs.androidx.datastore.preferences)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.bundles.compose)
    implementation(libs.androidx.compose.material3)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.bundles.coil)
    implementation(libs.bundles.ktor)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.bundles.credentials)
    implementation(libs.androidx.browser)
    implementation(libs.androidx.work.runtime.ktx)
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.messaging)

    testImplementation(libs.junit)
    testImplementation(libs.ktor.client.mock)
    testImplementation(libs.kotlinx.coroutines.test)
}
